## Dockerized AEM publisher image

FROM docker-tam-dev.dr.corp.adobe.com/aem-base:AEM6.1.0-SP1

MAINTAINER Robert Wunsch <wunsch@adobe.com>

ENV CQ_RUNMODE publish
ENV CQ_PORT 4503
ENV DEBUG_PORT 40404

RUN mv crx-quickstart/install-base/* crx-quickstart/install/

RUN echo sling.run.modes=${CQ_RUNMODE} >> crx-quickstart/conf/sling.properties && \
    crx-quickstart/bin/start && \
    until $(curl -u admin:admin --output /dev/null --silent --head --fail http://localhost:$CQ_PORT); do printf '.'; sleep 5; done && \
    crx-quickstart/bin/stop

ENV JMX_PORT 4603
ENV DOCKER_IP 192.168.99.100
	
EXPOSE $CQ_PORT
EXPOSE $DEBUG_PORT
EXPOSE $JMX_PORT

## Linking the standard-out and error-out to the AEM logs.
## Doing so enables the "docker log" command to read the logs.
RUN ln -sf /dev/stdout crx-quickstart/logs/access.log
RUN ln -sf /dev/stderr crx-quickstart/logs//error.log

CMD java \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=$JMX_PORT \
	-Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
	-Dcom.sun.management.jmxremote.local.only=false \
	-Djava.rmi.server.hostname=$DOCKER_IP \
    -Djava.awt.headless=true \
	-XX:MaxPermSize=256M -Xms512m -Xmx2048m \
    -Xdebug \
	-agentlib:jdwp=transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=n \
	-jar $AEM_QUICKSTART_FILE -p $CQ_PORT -r $CQ_RUNMODE -nobrowser -verbose -nofork
