## Dockerized AEM base image
#FROM ubuntu:18.04
FROM phusion/baseimage:master

MAINTAINER Robert Wunsch <wunsch@adobe.com>

ARG JAVA_VERSION
ARG JAVA_FILENAME=jdk-8u181-linux-x64.tar.gz
ARG JAVA_JDK_FOLDERNAME

ENV JAVA_HOME /usr/lib/jvm/java-${JAVA_VERSION}-oracle
ENV DEBIAN_FRONTEND noninteractive

## Install updates and Java, ffMPEG, ImageMagick,Ghostscript and OpenSSL
## Libraries to install for Forms: expat libxcb freetype libXau libSM zlib libICE libuuid glibc libXext nss-softokn-freebl fontconfig libX11 libXrender libXrandr libXinerama && \ 
## Forms dependecies from documentation: https://docs.adobe.com/content/help/en/experience-manager-64/forms/install-aem-forms/osgi-installation/install-configure-document-services.html#System%20Requirements
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y curl unzip software-properties-common imagemagick ffmpeg ghostscript openssl net-tools && \
    apt-get install -y libexpat1 libxcb1 freetype2-demos libxau6 libsm6 zlib1g libice6 libuuid1 libc6 libxext6 libnss3 fontconfig libx11-6 libxrender1 libxrandr2 libxinerama1 && \ ## Forms dependecies: https://git-corp/aemforms-on-ethos/forms-docker/blob/master/images/forms/src/main/docker/installDependencies.sh
    apt-get clean && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  

## Install Oracle JDK
#COPY ./${JAVA_FILENAME} /tmp/
ADD http://mirror.cnop.net/jdk/linux/${JAVA_FILENAME} /tmp/
RUN mkdir /opt/jdk/ && \ 
    mv /tmp/${JAVA_FILENAME} /opt/jdk/ && \
    cd /opt/jdk/ && \
    ls -lah /opt/jdk/ && \
    tar -xvzf ${JAVA_FILENAME} && \
    rm -rf ${JAVA_FILENAME} && \
    update-alternatives --install /usr/bin/java java /opt/jdk/${JAVA_JDK_FOLDERNAME}/bin/java 100 && \
    update-alternatives --install /usr/bin/javac javac /opt/jdk/${JAVA_JDK_FOLDERNAME}/bin/javac 100 
	
ENV JAVA_HOME=/opt/jdk/${JAVA_JDK_FOLDERNAME}
	
ARG ARTIFACTORY_USER_COLON_API_TOKEN

ARG AEM_QUICKSTART_VERSION
ENV AEM_QUICKSTART_VERSION=$AEM_QUICKSTART_VERSION

ARG AEM_QUICKSTART_FILE=cq-quickstart-${AEM_QUICKSTART_VERSION}.jar
ENV AEM_QUICKSTART_FILE=$AEM_QUICKSTART_FILE

#ARG AEM_USER=aem
ARG AEM_WORKING_DIR=/opt/aem

	
## Add quick-start file and license properties
COPY ./${AEM_QUICKSTART_FILE} ${AEM_WORKING_DIR}/${AEM_QUICKSTART_FILE}
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/day/cq/cq-quickstart/${AEM_QUICKSTART_VERSION}/${AEM_QUICKSTART_FILE} ${AEM_WORKING_DIR}/
COPY ./license.properties ${AEM_WORKING_DIR}/license.properties

## Create user and unpack AEM quick-start
#RUN groupadd -r ${AEM_USER} && useradd -r -g ${AEM_USER} ${AEM_USER} -d ${AEM_WORKING_DIR} && \
#    java -Djava.awt.headless=true -Xms2g -Xmx2g -jar ${AEM_WORKING_DIR}/${AEM_QUICKSTART_FILE} -unpack   && \
#    chown -R ${AEM_USER}:${AEM_USER} ${AEM_WORKING_DIR} 
#	&& \
#	echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
#    chmod 0440 /etc/sudoers.d/user
RUN java -Djava.awt.headless=true -Xms2g -Xmx2g -jar ${AEM_WORKING_DIR}/${AEM_QUICKSTART_FILE} -unpack

## Add install folder 
ADD install ${AEM_WORKING_DIR}/crx-quickstart/install/

## Add additional files to install folder
### -- Service Packs --
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP1/aem-service-pkg-6.0.SP1.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP2/aem-service-pkg-6.0.SP2.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP3/aem-service-pkg-6.0.SP3.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.1.SP1/aem-service-pkg-6.1.SP1.zip  ${AEM_WORKING_DIR}/install-base/	
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.1.SP2/aem-service-pkg-6.1.SP2.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.2.SP1/aem-service-pkg-6.2.SP1.zip ${AEM_WORKING_DIR}/install-base/

### -- CFPs ---
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/2.0/cq-6.1.0-sp2-cfp-2.0.zip ${AEM_WORKING_DIR}/install-base/	
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/3.0/cq-6.1.0-sp2-cfp-3.0.zip ${AEM_WORKING_DIR}/install-base/
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/11.2/cq-6.1.0-sp2-cfp-11.2.zip ${AEM_WORKING_DIR}/install-base/
	
#RUN chown -R ${AEM_USER}:${AEM_USER} ${AEM_WORKING_DIR}	
	
#USER ${AEM_USER}
WORKDIR ${AEM_WORKING_DIR}
