## Dockerized AEM publisher image
ARG AEM_VERSION
FROM docker-tam-dev.dr.corp.adobe.com/aem-base:AEM${AEM_VERSION}

MAINTAINER Robert Wunsch <wunsch@adobe.com>

ARG CQ_RUNMODE=publish
ARG CQ_PORT=4503

ENV CQ_RUNMODE=$CQ_RUNMODE
ENV CQ_PORT=$CQ_PORT

RUN echo sling.run.modes=${CQ_RUNMODE} >> crx-quickstart/conf/sling.properties && \
    crx-quickstart/bin/start && \
    until $(curl -u admin:admin --output /dev/null --silent --head --fail http://localhost:${CQ_PORT}); do printf '.'; sleep 5; done && \
	curl -u admin:admin -FtransportUri="http://dispatcher:80/dispatcher/invalidate.cache"  http://localhost:4503/etc/replication/agents.publish/flush/jcr:content && \
	curl -u admin:admin -Fenabled="true"  http://localhost:4503/etc/replication/agents.publish/flush/jcr:content && \
	## DO INITIAL SET-UP CURL STUFF HERE
    crx-quickstart/bin/stop

ENV DEBUG_HOST=127.0.0.1
ENV DEBUG_PORT=40404
ENV JMX_PORT=4603
ENV JMX_IP=0.0.0.0
ENV HEAP_SIZE=2048m
	
EXPOSE ${CQ_PORT}
EXPOSE ${DEBUG_PORT}
EXPOSE ${JMX_PORT}

## Linking the standard-out and error-out to the AEM logs.
## Doing so enables the "docker log" command to read the logs.
RUN ln -sf /dev/stdout crx-quickstart/logs/access.log
RUN ln -sf /dev/stderr crx-quickstart/logs/error.log

CMD java \
	-server \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=${JMX_PORT} \
	-Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
	-Dcom.sun.management.jmxremote.local.only=false \
	-Djava.rmi.server.hostname=${JMX_IP} \
    -Djava.awt.headless=true \
	-XX:MaxPermSize=256M -Xms${HEAP_SIZE} -Xmx${HEAP_SIZE} \
	-XX:+PrintGC \
	-XX:+HeapDumpOnOutOfMemoryError \
	-XX:HeapDumpPath=${AEM_WORKING_DIR}/logs \
	-agentlib:jdwp=transport=dt_socket,address=${DEBUG_PORT},server=y,suspend=n \
	-jar ${AEM_QUICKSTART_FILE} -p ${CQ_PORT} -r ${CQ_RUNMODE} -nobrowser -verbose -nofork
