## Dockerized AEM base image
#FROM ubuntu:18.04
FROM phusion/baseimage:0.11

MAINTAINER Robert Wunsch <wunsch@adobe.com>

ARG JAVA_VERSION
ARG JAVA_FILENAME
ARG JAVA_JDK_FOLDERNAME

ENV JAVA_HOME /usr/lib/jvm/java-${JAVA_VERSION}-oracle
ENV DEBIAN_FRONTEND noninteractive

## Install updates and Java, ffMPEG, ImageMagick and Ghostscript
#RUN apt-get update && \
#    apt-get -y upgrade && \
#    apt-get install -y curl unzip software-properties-common imagemagick ffmpeg ghostscript && \
#	echo oracle-java${JAVA_VERSION}-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
#    apt-get clean && \
#    apt-get purge && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* && \
    
## Install Oracle JDK
COPY ./${JAVA_FILENAME} /tmp/
RUN mkdir /opt/jdk/ && \ 
    mv /tmp/${JAVA_FILENAME} /opt/jdk/ && \
    cd /opt/jdk/ && \
    ls -lah /opt/jdk/ && \
    tar -xvzf ${JAVA_FILENAME} && \
    rm -rf ${JAVA_FILENAME} && \
    update-alternatives --install /usr/bin/java java /opt/jdk/${JAVA_JDK_FOLDERNAME}/bin/java 100 && \
    update-alternatives --install /usr/bin/javac javac /opt/jdk/${JAVA_JDK_FOLDERNAME}/bin/javac 100 
	
ARG ARTIFACTORY_USER_COLON_API_TOKEN

ARG AEM_VERSION=6.4.0
ARG AEM_QUICKSTART_FILE=cq-quickstart-${AEM_VERSION}.jar
ARG AEM_USER=aem
ARG AEM_WORKING_DIR=/opt/aem

ENV AEM_QUICKSTART_FILE=$AEM_QUICKSTART_FILE
ENV AEM_VERSION=$AEM_VERSION
	
## Add quick-start file and license properties
COPY ./${AEM_QUICKSTART_FILE} ${AEM_WORKING_DIR}/${AEM_QUICKSTART_FILE}
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/day/cq/cq-quickstart/${AEM_VERSION}/${AEM_QUICKSTART_FILE} ${AEM_WORKING_DIR}/
COPY ./license.properties ${AEM_WORKING_DIR}/license.properties

## Create user and unpack AEM quick-start
RUN groupadd -r ${AEM_USER} && useradd -r -g ${AEM_USER} ${AEM_USER} -d ${AEM_WORKING_DIR} && \
    java -Djava.awt.headless=true -Xms2g -Xmx2g -jar ${AEM_WORKING_DIR}/${AEM_QUICKSTART_FILE} -unpack   && \
    chown -R ${AEM_USER}:${AEM_USER} ${AEM_WORKING_DIR} 
#	&& \
#	echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
#    chmod 0440 /etc/sudoers.d/user

## Add install folder 
ADD install ${AEM_WORKING_DIR}/crx-quickstart/install/

## Add additional files to install folder
### -- Service Packs --
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP1/aem-service-pkg-6.0.SP1.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP2/aem-service-pkg-6.0.SP2.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.0.SP3/aem-service-pkg-6.0.SP3.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.1.SP1/aem-service-pkg-6.1.SP1.zip  ${AEM_WORKING_DIR}/install-base/	
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.1.SP2/aem-service-pkg-6.1.SP2.zip ${AEM_WORKING_DIR}/install-base/
#ADD  https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/aem-service-pkg/6.2.SP1/aem-service-pkg-6.2.SP1.zip ${AEM_WORKING_DIR}/install-base/

### -- CFPs ---
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/2.0/cq-6.1.0-sp2-cfp-2.0.zip ${AEM_WORKING_DIR}/install-base/	
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/3.0/cq-6.1.0-sp2-cfp-3.0.zip ${AEM_WORKING_DIR}/install-base/
#ADD https://artifactory.corp.adobe.com/artifactory/maven-aem-release-local/com/adobe/cq/cumulativefixpack/cq-6.1.0-sp2-cfp/11.2/cq-6.1.0-sp2-cfp-11.2.zip ${AEM_WORKING_DIR}/install-base/
	
RUN chown -R ${AEM_USER}:${AEM_USER} ${AEM_WORKING_DIR}	
	
USER ${AEM_USER}
WORKDIR ${AEM_WORKING_DIR}
